# Inspired from https://blog.orhun.dev/zig-bits-03/
# Updated to Zig 0.13.0
name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  install-zig:
    name: Install zig
    runs-on: ubuntu-latest
    steps:
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.13.0

  publish-github:
    name: Publish on GitHub
    runs-on: ubuntu-latest
    needs: install-zig
    strategy:
      fail-fast: false
      matrix:
        TARGET:
          [
            x86_64-linux,
            aarch64-linux,
            arm-linux
          ]

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Build
        run: zig build --release=small -Dtarget=${{ matrix.TARGET }} --summary all

      - run: tree ./zig-out

      - name: Upload the binary
        uses: svenstaro/upload-release-action@v2
        with:
          tag: ${{ github.ref }}
          file: zig-out/bin/waybar-wise-fx-rate
          asset_name: waybar-wise-fx-rate-${{ matrix.TARGET }}
          overwrite: true
          repo_token: ${{ secrets.WAYBAR_WISE_FX_RATE_PAT }}
